-- 1. Use the Super Admin role
USE ROLE ACCOUNTADMIN;

-- 2. Force Create everything one last time to be safe
CREATE OR REPLACE DATABASE INSPECTION_DB;
CREATE OR REPLACE SCHEMA INSPECTION_DB.APP;

-- 3. GRANT THE MISSING PRIVILEGES (This fixes your error!)
GRANT USAGE ON DATABASE INSPECTION_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA INSPECTION_DB.APP TO ROLE ACCOUNTADMIN;
GRANT CREATE STREAMLIT ON SCHEMA INSPECTION_DB.APP TO ROLE ACCOUNTADMIN;
GRANT CREATE STAGE ON SCHEMA INSPECTION_DB.APP TO ROLE ACCOUNTADMIN;

-- 4. Enable the AI engine
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
